# Generated by Django 2.1.5 on 2020-10-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('ram', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'Mobile'), (1, 'Laptop')])),
                ('processor', models.CharField(max_length=10)),
            ],
        ),
    ]
