# Generated by Django 2.1.5 on 2020-10-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop')]),
        ),
    ]
