# Generated by Django 2.1.5 on 2020-10-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201013_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(0, 'Mobile'), (1, 'Laptop')]),
        ),
    ]
